'----------------------------------------------------------------------------
'Ý                             Pickers Games                                 Ý
'Ý                             -------------                                 Ý
'Ý                                                                           Ý
'Ý                       Color was made by Pickers Games                     Ý
'Ý                                                                           Ý
'Ý  Pickers Games can be found at                                            Ý
'Ý                                  http://www.pickersgames.co.uk            Ý
'Ý                                  ------------------------------           Ý
'Ý                                                                           Ý
'Ý                                                                           Ý
'ÝThis Program includes 5 examples of the color statement, all you have to   Ý
'Ýdo is change the numbers for differen colors!!                             Ý                      
'Ý                                                                           Ý
'Ý                                PRESS F5 TO RUN                            Ý
'Ý                                ---------------                            Ý
'Ý                                                                           Ý
'Ý___________________________________________________________________________Ý

'Change the numbers for different colors!!
CLS
PRINT "this is a test of colors please DON'T press a key": SLEEP 3
COLOR 1, 2, 3
PRINT "color 1": SLEEP 1
COLOR 8, 3, 4
PRINT "color 2": SLEEP 1
COLOR 11, 6, 3
PRINT "color 3": SLEEP 1
COLOR 28, 6, 5
PRINT "color 4": SLEEP 1
COLOR 10, 2, 3
PRINT "color 5": SLEEP 1

